// This file was auto-generated by ML.NET Model Builder. 
using Microsoft.ML;
using Microsoft.ML.Data;
using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
namespace CreditScore_ML
{
    public partial class MLCreditScoringModel
    {
        /// <summary>
        /// model input class for MLCreditScoringModel.
        /// </summary>
        #region model input class
        public class ModelInput
        {
            [ColumnName(@"V1")]
            public float V1 { get; set; }

            [ColumnName(@"V2")]
            public float V2 { get; set; }

            [ColumnName(@"V3")]
            public float V3 { get; set; }

            [ColumnName(@"V4")]
            public float V4 { get; set; }

            [ColumnName(@"V5")]
            public float V5 { get; set; }

            [ColumnName(@"V6")]
            public float V6 { get; set; }

            [ColumnName(@"V7")]
            public float V7 { get; set; }

            [ColumnName(@"V8")]
            public float V8 { get; set; }

            [ColumnName(@"V9")]
            public float V9 { get; set; }

            [ColumnName(@"V10")]
            public float V10 { get; set; }

            [ColumnName(@"V11")]
            public float V11 { get; set; }

            [ColumnName(@"V12")]
            public float V12 { get; set; }

            [ColumnName(@"V13")]
            public float V13 { get; set; }

            [ColumnName(@"V14")]
            public float V14 { get; set; }

            [ColumnName(@"Fracaso")]
            public float Fracaso { get; set; }

        }

        #endregion

        /// <summary>
        /// model output class for MLCreditScoringModel.
        /// </summary>
        #region model output class
        public class ModelOutput
        {
            [ColumnName("PredictedLabel")]
            public float Prediction { get; set; }

            public float[] Score { get; set; }
        }

        #endregion

        private static string MLNetModelPath = Path.GetFullPath("MLCreditScoringModel.zip");

        public static readonly Lazy<PredictionEngine<ModelInput, ModelOutput>> PredictEngine = new Lazy<PredictionEngine<ModelInput, ModelOutput>>(() => CreatePredictEngine(), true);

        /// <summary>
        /// Use this method to predict on <see cref="ModelInput"/>.
        /// </summary>
        /// <param name="input">model input.</param>
        /// <returns><seealso cref=" ModelOutput"/></returns>
        public static ModelOutput Predict(ModelInput input)
        {
            var predEngine = PredictEngine.Value;
            return predEngine.Predict(input);
        }

        private static PredictionEngine<ModelInput, ModelOutput> CreatePredictEngine()
        {
            var mlContext = new MLContext();
            ITransformer mlModel = mlContext.Model.Load(MLNetModelPath, out var _);
            return mlContext.Model.CreatePredictionEngine<ModelInput, ModelOutput>(mlModel);
        }
    }
}
