﻿// This file was auto-generated by ML.NET Model Builder. 
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Microsoft.ML.Data;
using Microsoft.ML.Trainers.FastTree;
using Microsoft.ML.Trainers;
using Microsoft.ML;

namespace CreditScore_ML
{
    public partial class MLModel1
    {
        public static ITransformer RetrainPipeline(MLContext context, IDataView trainData)
        {
            var pipeline = BuildPipeline(context);
            var model = pipeline.Fit(trainData);

            return model;
        }

        /// <summary>
        /// build the pipeline that is used from model builder. Use this function to retrain model.
        /// </summary>
        /// <param name="mlContext"></param>
        /// <returns></returns>
        public static IEstimator<ITransformer> BuildPipeline(MLContext mlContext)
        {
            // Data process configuration with pipeline data transformations
            var pipeline = mlContext.Transforms.ReplaceMissingValues(new []{new InputOutputColumnPair(@"Type of fund", @"Type of fund"),new InputOutputColumnPair(@"Lifetime", @"Lifetime"),new InputOutputColumnPair(@"World private equity", @"World private equity"),new InputOutputColumnPair(@"Log World private equity", @"Log World private equity"),new InputOutputColumnPair(@"Gross annual MSCI return", @"Gross annual MSCI return"),new InputOutputColumnPair(@"GDP Germany", @"GDP Germany"),new InputOutputColumnPair(@"GPD US", @"GPD US"),new InputOutputColumnPair(@"Germany interest rate", @"Germany interest rate"),new InputOutputColumnPair(@"US interest rate", @"US interest rate"),new InputOutputColumnPair(@"Fund size", @"Fund size"),new InputOutputColumnPair(@"Log fund size", @"Log fund size"),new InputOutputColumnPair(@"Geography focus", @"Geography focus"),new InputOutputColumnPair(@"Region fund manager", @"Region fund manager"),new InputOutputColumnPair(@"Diversification", @"Diversification"),new InputOutputColumnPair(@"Industry focus", @"Industry focus"),new InputOutputColumnPair(@"Assets under the manager", @"Assets under the manager")})      
                                    .Append(mlContext.Transforms.Concatenate(@"Features", new []{@"Type of fund",@"Lifetime",@"World private equity",@"Log World private equity",@"Gross annual MSCI return",@"GDP Germany",@"GPD US",@"Germany interest rate",@"US interest rate",@"Fund size",@"Log fund size",@"Geography focus",@"Region fund manager",@"Diversification",@"Industry focus",@"Assets under the manager"}))      
                                    .Append(mlContext.Transforms.NormalizeMinMax(@"Features", @"Features"))      
                                    .Append(mlContext.Regression.Trainers.FastTreeTweedie(new FastTreeTweedieTrainer.Options(){NumberOfLeaves=4,MinimumExampleCountPerLeaf=40,NumberOfTrees=182,MaximumBinCountPerFeature=258,FeatureFraction=0.729076789794998,LearningRate=0.9989577419979,LabelColumnName=@"Cash multiple",FeatureColumnName=@"Features"}));

            return pipeline;
        }
    }
}
